# Generated by Django 3.0.5 on 2020-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
